### ISSUE TITLE
Error running javaScript examples

### ISSUE THREAD

**Issue by KeithKarnage** [gamestdio/colyseus-examples#7]
I tried cloning and running as suggested and ran into this error:

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/keithkarnage/Documents/colyseus-examples/node_modules/colyseus/lib/index.js:8:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by endel** [comment]
Hi @KeithKarnage, which version of Node.js are you using?

I couldn't reproduce here. My Node version is `v8.7.0`. Cheers

**Comment by KeithKarnage** [comment]
That did the trick.  Thanks for quickly responding to my rookie mistake!
